[tool.poetry]
name = "pong-pygame"
version = "0.1.0"
description = "Pong implemented using pygame"
authors = ["Danny Solivan <dark@nightconcept.net>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame-ce = "^2.5.1"
esper = "^3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
